behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 8192
      buffer_size: 81920  
      learning_rate: 0.0003
      beta: 0.01  
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5  
      learning_rate_schedule: linear  
    network_settings:
      normalize: true  
      hidden_units: 1024 
      num_layers: 3  
      vis_encode_type: resnet 
      inference_device: gpu
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 1500 
    summary_freq: 10000
    self_play:
      save_steps: 10000
      team_change: 200000
      swap_steps: 2000
      window: 30 
      play_against_latest_model_ratio: 0.85  
      initial_elo: 1200.0